class ostack_controller::install (
     $dbtype  = 'mysql',
     $dbhost  = 'ostackdb',
     $keystonedbname  = 'keystone',
     $keystonedbuser  = 'keystone',
     $keystonedbpass  = 'keatomos3',
     $keystonedbhost  = $dbhost,
     $glancedbname  = 'glance',
     $glancedbuser  = 'glance',
     $glancedbpass  = 'glatomos3',
     $glancedbhost  = $dbhost,
     $novadbname  = 'nova',
     $novaapidbname  = 'nova_api',
     $novadbuser  = 'nova',
     $novadbpass  = 'noatomos3',
     $novadbhost  = $dbhost,
     $neutrondbname  = 'neutron',
     $neutrondbuser  = 'neutron',
     $neutrondbpass  = 'neatomos3',
     $neutrondbhost  = $dbhost,
     $glanceuser  = $dbuser,
     $glancepass  = $dbpass,
     $novauser  = $dbuser,
     $novapass  = $dbpass,
     $placemuser  = 'placement',
     $placempass  = 'platomos3',
     $neutronuser  = $neutrondbuser,
     $neutronpass  = $neutrondbpass,
     $admindbpass = 'keatomos3',
     $metadatapass = 'meatomos3',
     $memcache_host = 'memcache',
     $controller_host = 'controller',
     $mq_proto = 'rabbit',
     $mq_user  = 'openstack',
     $mq_pass  = 'raatomos3',
     $mq_host  = 'rabbitmq',
     $ostack_region       = 'RegionOne',
     $bstp_adm_port       = '35357/v3/',
     $bstp_int_port       = '5000/v3/',
     $bstp_pub_port       = '5000/v3/',
     $nova_adm_port       = '8774/v2.1',
     $nova_int_port       = '8774/v2.1',
     $nova_pub_port       = '8774/v2.1',
     $placem_adm_port     = '8778',
     $placem_int_port     = '8778',
     $placem_pub_port     = '8778',
     $glance_adm_port     = '9292',
     $glance_int_port     = '9292',
     $glance_pub_port     = '9292',
     $neutron_adm_port    = '9696',
     $neutron_int_port    = '9696',
     $neutron_pub_port    = '9696',
     $memcache_port       = '11211',
     $service_proj_descr = "Service Project",
     $glance_service_descr = "OpenStack Image",
     $nova_service_descr = "OpenStack Compute",
     $placem_service_descr = "Placement API",
     $neutron_service_descr = "OpenStack Networking",
) {
######
   # Definition of databases by the controller host which is also DB administrator
   # keystone identity service
   ostack_controller::install::keystone { 'keystone':
     dbtype  => $dbtype,
     dbname  => $keystonedbname,
     dbuser  => $keystonedbuser,
     dbpass  => $keystonedbpass,
     dbhost  => $keystonedbhost,
     admindbpass  => $admindbpass,
     controller_host => $controller_host,
     before  => Ostack_controller::Install::Glance['glance'],
   }

   # glance image service (note admin pass = keystone identity service)
   ostack_controller::install::glance { 'glance':
     dbtype  => $dbtype,
     dbname  => $glancedbname,
     dbuser  => $glancedbuser,
     dbpass  => $glancedbpass,
     dbhost  => $glancedbhost,
     admindbpass  => $admindbpass,
     controller_host => $controller_host,
     before  => Ostack_controller::Install::Nova['nova'],
   }
   # nova compute service (note admin pass = keystone identity service)
   ostack_controller::install::nova { 'nova':
     dbtype  => $dbtype,
     dbname  => $novadbname,
     dbuser  => $novadbuser,
     dbpass  => $novadbpass,
     dbhost  => $novadbhost,
     admindbpass  => $admindbpass,
     controller_host => $controller_host,
     memcache_host => $memcache_host,
     mq_user  => $mq_user,
     mq_pass  => $mq_pass,
     mq_host  => $mq_host,
     before  => Ostack_controller::Install::Neutron['neutron'],
   }
   # neutron network service (note admin pass = keystone identity service)
   ostack_controller::install::neutron { 'neutron':
     dbtype  => $dbtype,
     dbname  => $neutrondbname,
     dbuser  => $neutrondbuser,
     dbpass  => $neutrondbpass,
     dbhost  => $neutrondbhost,
     admindbpass  => $admindbpass,
     controller_host => $controller_host,
     memcache_host => $memcache_host,
     mq_user  => $mq_user,
     mq_pass  => $mq_pass,
     mq_host  => $mq_host,
   }
}
